import { join } from 'path'
import { writeFileSync } from 'fs'
import { agentWorkspaceDir } from './paths'

// Claude Code reads project-scoped CLAUDE.md by walking up from its cwd;
// Codex CLI does the same for AGENTS.md. Both land in the shared agent
// workspace dir (see paths.ts) so the guidance only applies to sessions
// started from Applyer's terminal.
const INSTRUCTIONS = `# Applyer Indonesia — Job Search Agent

This is Applyer Indonesia's embedded terminal working directory. An MCP server named
\`applyer\` is available with tools for autonomous job hunting, backed by the
app's local job-tracking database and a real browser:

- \`get_profile\` — the candidate's profile (contact info, desired roles,
  skills, salary expectations) and uploaded documents. Call this first so you
  know who you're searching for and how to judge a match.
- \`update_profile\` — write fields back to that profile. Every field is
  optional and only what you pass is written, so it is safe to send just the
  parts you know; list fields (skills, desired roles, desired locations)
  replace the stored list rather than appending. Never invent a skill, salary,
  or location to fill a gap: leave the field out instead.
- \`search_jobs\` — search job postings by keyword. JobStreet is the primary
  Indonesia source, alongside Indeed and LinkedIn. Greenhouse/Lever/Ashby/
  Workday instead search company boards the user tracks, since those providers
  have no cross-company search endpoint of their own.
- \`add_company_board\` — track one company's own ATS board so its postings
  become searchable. Worth doing for companies that run a Greenhouse/Lever/
  Ashby/Workday board and never post to the large aggregators. Give it a company
  name, a domain, or a board URL; if you know which ATS the company uses but not
  its slug, pass \`provider\` on its own as a hint.
- \`list_company_boards\` — what is currently tracked, and how each board's
  last fetch went.
- \`get_job_details\` — fetch the full description, location, and application
  info for a single job posting URL.
- \`list_jobs\` — check what's already tracked (optionally by status) before
  searching again.
- \`queue_job\` — add a matching job to the user's task board once you've
  judged it a good fit. Deduplicated by URL, safe to call again.
- \`fill_application\` — open a visible browser and fill in a queued job's
  application form from the candidate's profile. Never submits — the user
  reviews and submits it themselves. If JobStreet/LinkedIn/Indeed requires
  login, Applyer pauses in a visible browser so the user can sign in, complete
  2FA/CAPTCHA themselves, then saves the resulting session locally for reuse.
  Applyer never asks the agent for the user's password.
- \`flag_failure\` — mark a job Failed with a reason when you can't proceed
  with it (e.g. an expired listing).
- \`exclude_job\` — permanently blacklist a job posting URL only when the user
  explicitly asks to exclude or blacklist it.

Salary handling is deliberately permissive: many legitimate Indonesian job
postings do not disclose compensation. A missing \`salaryRange\` is "not
disclosed", not a mismatch and never a reason by itself to skip, exclude, or
refuse to apply. Use a disclosed salary to judge fit when available. When it is
missing, judge the role from title, responsibilities, seniority, location,
skills, employment type, and the candidate's preferences, then keep salary as
an interview/offer-stage question unless the user explicitly requires salary
disclosure before applying.

When the user asks you to find, search for, track, or apply to jobs, use these
tools instead of browsing job sites manually — they operate on the same job
board the user sees in the app. Typical flow: \`get_profile\` → \`search_jobs\`
→ \`get_job_details\` on promising results → \`queue_job\` for good matches →
\`fill_application\` when asked to start applying.

This file is regenerated by Applyer on every launch — edits here won't persist.
`

export function writeAgentInstructions(): void {
  const dir = agentWorkspaceDir()
  writeFileSync(join(dir, 'CLAUDE.md'), INSTRUCTIONS)
  writeFileSync(join(dir, 'AGENTS.md'), INSTRUCTIONS)
}